print("Jogo Mad Lib")
print()
print()
print('Título: "UM DIA INESPERADO"')
print("Complete a história com as palavras, conforme a solicitação do programa:")
print()
adjetivo1 = input("Digite um ADJETIVO: ")
substantivo = input("Digite um SUBSTANTIVO: ")
adjetivo2 = input("Digite outro ADJETIVO: ")
verbo1 = input("Digite um VERBO no infinitivo: ")
lugar = input("Digite um LUGAR: ")
pessoa = input("Digite uma PESSOA: ")
verbo2 = input("Digite um VERBO no gerúndio: ")
adjetivo3 = input("Digite mais um ADJETIVO: ")
print()
print("Hoje acordei me sentindo muito " + adjetivo1 +".")
print("Olhei pela janela e vi um(a) " + substantivo, adjetivo2 + " passando pela rua.")
print("Decidi " + verbo1 + " rapidamente, porque estava atrasado para o(a) " + lugar +".")
print("No caminho, encontrei meu/minha " + pessoa +", que estava " + verbo2 + " como se não houvesse amanhã.")
print("No final do dia, percebi que foi o dia mais " + adjetivo3 + " da minha vida.")